export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'




export const BOOKING_GET_REQUEST = 'BOOKING_GET_REQUEST'
export const BOOKING_GET_SUCCESS = 'BOOKING_GET_SUCCESS'
export const BOOKING_GET_FAIL = 'BOOKING_GET_FAIL'



export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

