export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'




export const BOOKING_GET_REQUEST = 'BOOKING_GET_REQUEST'
export const BOOKING_GET_SUCCESS = 'BOOKING_GET_SUCCESS'
export const BOOKING_GET_FAIL = 'BOOKING_GET_FAIL'